### ISSUE TITLE
Set up the application icon (Btchap/Tchap/Tchap secure)

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#102]
Replace the element icon with the right Tchap one

For example [this icon](https://github.com/tchapgouv/tchap-android-v2/blob/develop/vector/src/agent/res/drawable-xxhdpi/logo_tchap_color.png) for the variant agent,
or [this one](https://github.com/tchapgouv/tchap-android-v2/blob/develop/vector/src/preprod/res/drawable-xxhdpi/logo_tchap_color.png) for Btchap (preprod)

**Comment by Florian14** [comment]
Waiting for app icons in several resolutions and their rounded version

**Comment by yostyle** [comment]
TODO add variants (preprod and secure) dynamic icons.
