### ISSUE TITLE
[Home screen] Set up the (+) button on the rooms list

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#109]
We want here to replace the floating button displayed on the rooms list:
![image](https://user-images.githubusercontent.com/8969772/123000134-77592300-d3af-11eb-8f14-2b39ce72e0cc.png)
with a (+) button like in tchap v1. This kind of button is currently displayed on the third tab "Notifications":
![image](https://user-images.githubusercontent.com/8969772/123000285-ad96a280-d3af-11eb-87d5-1838165a27ef.png)

When the user clicks on this (+) button, 3 options are displayed with the icons available in [tchap v1](https://github.com/tchapgouv/tchap-android/blob/develop/vector/src/main/res/layout/activity_home.xml#L147) or extracted from design v4, but with the new following wording:
- Nouveau message direct
- Nouveau salon/forum
- Rejoindre un forum depuis l’annuaire 

**Caution: this floating button is hidden for the external users** (see [tchap v1](https://github.com/tchapgouv/tchap-android/blob/develop/vector/src/main/java/im/vector/activity/VectorHomeActivity.java#L598))

The action relative to each option will be added later. For the moment the existing action is connected to the last option "rejoindre un forum...".

**Comment by Florian14** [comment]
Waiting for this change to be released in Element-Android: vector-im#3636
