### ISSUE TITLE
[Direct] Update DM created to invite new user by email with the actual matrix id 

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#128]
Currently the DM created to invite someone by email is stuck on the email address in the `m.direct` dictionary of the account data -> the `directUserId` is stuck on the email address even when an account has been bound to this email.
An action has to be planned to update the `m.direct` dictionary

First step: reproduce the issue in Element-Android in order to fix this in the mainline after checking it with the Platform team

**Comment by Florian14** [comment]
An issue has been created in Element-Android to update the AccountData when the invited user has joined element: https://github.com/vector-im/element-android/issues/3643
