### ISSUE TITLE
Set up the permalink option

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#137]
Like we did in Tchap V1 [here](https://github.com/tchapgouv/tchap-android/pull/576), we don't want to use "matrix.to" prefix in the Tchap permalink:
- remove "matrix.to" use (keep supporting it internally to manage the reply_to mechanism)
- define a different permalink prefix for each target (secure/agent/preprod)

**Comment by yostyle** [comment]
Permalinks creation are managed in matrix sdk and we have no option to configure it. Perhaps an update on Element android is needed.
