### ISSUE TITLE
Upgrade Tchap-Android application with Tchap V2 code base

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#140]
We plan in few month to upgrade the Tchap-Android application with the Tchap V2 codebase, and to properly migrate the existing account data to let users enjoy the new version of the app without having to log in again.

This process had been already done for Riot, the plan is available [here](https://github.com/vector-im/element-android/issues/1273)

The first step is to prepare here a similar plan( checklist) for Tchap V2.
The second step is to check in the Element-Android code if the migration code is still available

**Comment by yostyle** [comment]
The decision has been taken to upgrade the Tchap application based on Riot with the Element codebase, and to properly migrate the existing account data to let users enjoy the new version of the app without having to log in again.

Here are the identified steps so far:

#### on the Element codebase:

- [x] 1. Replace Element ApplicationId by Tchap ApplicationIds on each variant. No need to rename the folder of the source code.
- [ ] 2. Import previous credentials to let logged user stay connected after the upgrade of there TchapV1 application
- [ ] 3. Import the previous crypto database to avoid users loosing there keys after the upgrade
The two last steps should not impact the user and should be transparent for him.
- [ ] 4. There is no need to migrate the session store. An initial sync will be performed.
- [ ] 5. Cleanup all the previous files created by the legacy codebase and not used anymore by the Element codebase.
- [ ] 6. Check permissions. Some permissions may have been already granted to TchapV1 (ex: read_contact), and not used yet in Element. If we remove them from the manifest during the upgrade, we will ask again the user to use the permission in the future. So add them now to the TchapV2 Android Manifest to keep the user grant access allowance.
**EDIT**: permissions will be added when we will add the feature which require them
- [ ] 7. VersionCode: ensure current version code generation of TchapV2 is compatible to generate an update of TchapV1
- [ ] 9. SecureStorage: this is a point, study what are the problematics and how we can handle it
- [ ] 10. User agent: restore user agent of TchapV1 on TchapV2?
- [ ] 11. RageShake: study impact
- [x] 12. Replace Element appname by Tchap appname on each variant.
- [x] 13. Icons. Replace Element launcher icons by Tchap icons.
- [ ] 14. Outdated homeservers: Element does not support to get connected to outdated homeserver. [Lazy-loading of room members is required](https://github.com/vector-im/riotX-android/blob/fbde8d7d18d4d78433b0a8902a35f048e382afa4/matrix-sdk-android/src/main/java/im/vector/matrix/android/api/auth/data/Versions.kt#L67). [Other checks](https://github.com/vector-im/riotX-android/blob/fbde8d7d18d4d78433b0a8902a35f048e382afa4/matrix-sdk-android/src/main/java/im/vector/matrix/android/api/auth/data/Versions.kt#L74) are done to know if login and registration are supported by Element. So we have to deal with current users of TchapV1 who are connected to an outdated homeserver. The current idea is to check, during the migration process, if the homeserver is uptodate regarding Element codebase requirement, and if it is not the case, to warn the user about the fact that their homeserver has to be updated, for security reason, and that some features may not work properly. Though the access to the application should not be blocked anyway.

#### on the TchapV1 project:

- [ ] Nothing but update the README.md files to let people understand that the code will now die

#### Other steps to consider:

- [ ] Update PlayStore description of Tchap?

#### Identified limitations:

- [ ] TchapV1 in minSDK 16 and Element is minSDK 21. Every devices running API 20 and less will not get the upgrade of the application.
- [ ] Feature parity will not be reached when we will do the upgrade. This is assumed and the following releases will hopefully contains the remaining features. People really annoyed by this can still alternative client, like miniVector (which I know is deliberately missing some features) or download the legacy application from other stores like F-Droid

#### F-Droid store

- [ ] F-Droid store is also hosting a version of the application. I assume it will be the same than for the PlayStore: TchapV2 codebase should replace TchapV1 application.

**Comment by yostyle** [comment]
https://github.com/tchapgouv/tchap-android-v2/issues/164

**Comment by giomfo** [comment]
The first steps have been done. The upgrade task will now be tracked by #164
