### ISSUE TITLE
[Self verification] Be able to verify a new session in TchapV2 from an old session

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#166]
we observed the following issue:

When we connect an account in Tchap v2, we are prompted to check this new session but nothing is displayed on existing sessions (in Tchap-Android v1)

Several use cases must be tested here
new session v1 against existing session v1
new session v1 against existing session v2
new session v2 against existing session v2
new session v2 against existing session v1

**Comment by yostyle** [comment]
https://github.com/tchapgouv/tchap-android-v2/blob/bded40535ab831fdafb16664b6479a76ae93b381/vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt#L200
