### ISSUE TITLE
Adjust the design in the room details screen

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#168]
We will use the following screenshot to compare the rendering of a room in the 2 versions of Tchap:
![image](https://user-images.githubusercontent.com/8969772/129394128-701cf3a6-078e-4dd8-95ab-8990229ab173.png)

I suggest the following changes in TchapV2:
In the room header:
~~- [ ] display an hexagonal avatar for the room which aren't DM (To be confirmed by the DINUM)~~
~~- [ ] display a padlock or the forum icon at the top right corner of the avatar according to the room type (private/forum) (To be confirmed by the DINUM)~~ This point will be handled later in another issue
~~- [ ] check with the Element Application team to make ellipsis less strict~~ fixed the ellipsis was due to invisible call icons
- [x] hide the shield at the bottom right corner of the avatar ~~(To be confirmed by the DINUM)~~

In the room history:
~~- [ ] display an hexagonal avatar for the room which aren't DM (To be confirmed by the DINUM)~~
- [x] hide the option "Ajouter un sujet" when the user is not allowed to edit the room topic (To be fixed in Element-Android)
- [x] hide the option "Ajouter des personnes" when the user is not allowed to invite new members (To be fixed in Element-Android)
- [x] hide from the room history the following room state event: `m.room.guest_access`
~~- [ ] check with the DINUM if we should still hide from the room history the following room state event: `m.room.join_rules`, `m.room.join_rules`, `m.room.history_visibility`, `m.room.encryption`~~
~~- [ ] check with the DINUM if we should hide `m.room.name` and `m.room.topic`~~

**Comment by giomfo** [comment]
some points will be handled by https://github.com/vector-im/element-android/issues/3959

**Comment by Anna-Livia** [comment]
A la création du salon, dans l'encart de sécurité, j'aimerais voir les messages suivants : 
Si chiffré : 
```
Chiffrement activé 
Les messages de ce salon sont chiffrés de bout en bout. l'historique ne sera pas accessible aux nouveaux participants. Apprenez en plus sur le chiffrement.
```
Si non chiffré : 
```
Chiffrement désactivé 
Les messages ne sont pas chiffrés. Les nouveaux participants auront accès à l'intégralité de l'historique.Apprenez en plus sur le chiffrement.
```

**Comment by Anna-Livia** [comment]
Les changement de topic, de nom de salon et de mode d'accès doivent être notifié dans l'historique.
Dans les salons privés, on devrait voir les arrivées de nouvelles personnes, quelles soient là par lien ou par invitations
