### ISSUE TITLE
[Cross signing] the feature is enabled while the keys are not reliable

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#172]
When we connect an existing Tchap account in TchapV2, we read in the app settings the following information about the cross signing:
![image](https://user-images.githubusercontent.com/8969772/130254467-0beae2b0-64b3-4ae6-9565-4b62f514e032.png)

We are ok that the cross signature is activated. But we do not understand why the keys are not reliable ...
In our case, just click on "Reset keys" update the keys and validate them for the cross-signing

2 questions:
- what does "enabled cross signing" mean if the keys are not reliable?
- is it possible to check whether a session has already set the keys? in order to reset them by default when none exists

**Comment by giomfo** [comment]
Note: if my current connexion is the only one, and if the secure storage is not enabled, we should reset automatically the cross-signing keys, because no MSK/SSKUSK can be retrieved from the account in this use case - To be confirmed

**Comment by yostyle** [comment]
"enabled cross signing" means that the cross signing public keys already exist. The keys are not reliable if the current session has not the cross signing private keys locally.

**Comment by yostyle** [comment]
Verification session flows :
![image](https://user-images.githubusercontent.com/1191674/132837703-4c7efa17-ff84-4f25-baa5-898fe0bd8335.png)

**Comment by giomfo** [comment]
We understood the point
