### ISSUE TITLE
Sanitize the logout mechanism 

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#194]
Currently the logout is unstable in Tchap V2, investigations are required

The DB clean is unsafe, some crashes are observed sometimes. This seems to be related to race conditions (check Element-Android on this point)

**Comment by giomfo** [comment]
@yostyle can you please add an update (ref to element-android issue) here

**Comment by yostyle** [comment]
> @yostyle can you please add an update (ref to element-android issue) here

https://github.com/vector-im/element-android/issues/4007

**Comment by giomfo** [comment]
Should be fixed since the last rebase (https://github.com/tchapgouv/tchap-android-v2/issues/252)
