### ISSUE TITLE
[Room Invite] Open the room when the user accepts the invite

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#233]
When I accept an invitation to a room, after the invite is processed I would expect to see the room. Instead it is hidden somewhere in my room list, forcing me to use search to find it

This is due to the current implementation in Element-Android (see [discussion](https://github.com/vector-im/element-android/issues/3771))

We will temporarily patch Tchap-Android to open the new joined room until Element-Android improves this behaviour.

**Comment by Claire1817** [comment]
PR on element: https://github.com/vector-im/element-android/pull/5247

**Comment by giomfo** [comment]
Will be fixed after a rebase against version >= https://github.com/vector-im/element-android/releases/tag/v1.4.2

**Comment by giomfo** [comment]
test ok
