### ISSUE TITLE
[Bug] Permalinks are not working correctly

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#259]
I sent several permalinks in a Tchap room, each time I clicked on them I got an error "malformed link"
 (I used for example "https://tchap.gouv.fr/#/room/#TchapWebUpdatesNotesdemisesjourzxipTNM:agent.intradef.tchap.gouv.fr" which is a forum link)

**Comment by Florian14** [comment]
Fixed in #237
