### ISSUE TITLE
[Room Member Details] Hide useless information

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#273]
In the room member details screen
![Screenshot_1636420293](https://user-images.githubusercontent.com/8969772/140843707-39a4a797-c524-4fc0-ad15-c1e05cb98ea9.png)

- [x] hide the matrix id 
- [x] hide the share icon displayed at the top right corner
- [x] hide the security shield
- [x] prevent display name clipping (use multiple lines if need) - this point should be fixed in Element-Android
- [x] hide the item "Vérifier" or "en savoir plus" dans la section "Sécurité"
- [x] hide the shield displayed over the avatar when the user scrolls up, the screen header is reduced
![image](https://user-images.githubusercontent.com/8969772/140844797-7c0a353a-35ea-4f87-a315-36af5de02b5e.png)

**Comment by ClaireGizard** [comment]
PR in Element: https://github.com/vector-im/element-android/pull/4700

**Comment by ClaireGizard** [comment]
PR in Element: https://github.com/vector-im/element-android/pull/4700
