### ISSUE TITLE
Tchap crashes during the forget password process

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#280]
I selected the forget password option from the login screen
I filled the email and the pwd, and submitted them
I'm prompted about the loss of the keys, I decided to continue -> crash (systematic)

**Comment by yostyle** [comment]
I didn't reproduce it on 'preprod'. Do you still have this crash since the rebase on element 1.3.8 ?

**Comment by ClaireGizard** [comment]
Cannot reproduced
