### ISSUE TITLE
[Self verification] Reset the cross-signing to unblock v2 verification

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#291]
About #166 (Be able to verify a new session in TchapV2 from an old session) we succeeded to verify a new session tchapv2 from an existing session v1 (see PR #200). But we observed the fix was not working if the cross-signing feature is enabled for the tested account. In that case the new session refuses to send key requests, so the session v1 doesn't detect the new session...
The cross-signing feature is not supposed to be enabled for a Tchap account, but it may be enabled if the user logged in once in Element application.

We added a specific log to track the potential case [here](https://github.com/tchapgouv/tchap-android-v2/blob/develop/vector/src/main/java/im/vector/app/features/home/HomeActivityViewModel.kt#L103)

I suggest triggering here a reset of this param from the account data, in order to unblock the verification of this new session tchapv2 from an existing session tchapv1

Before working on this task, you have to reproduce the case:
- connect with your Tchap account in Tchap v1 application (android for example)
- connect again with your Tchap account once on Element-web (the cross-signing is then enabled), you may logout from this session then
- connect your Tchap account in Tchapv2 -> the log "Cross signing feature is disabled. This account should not have cross signing keys" is displayed and nothing happens in the tchapv1 session -> NOK

**Comment by Florian14** [comment]
Reproduced by connecting to Tchap using Element-Android. There is no problem with Element-web. We'll ignore this issue for now as discussed IRL.

**Comment by giomfo** [comment]
After checking the DB, we realized only few users are concerned. Less than 300 Tchap users have the cross-signing enabled.
We decided to reduce the priority of this request
I close it for the moment, we may consider it later if the priority (or the impact) change
