### ISSUE TITLE
Support tagged events in Room Account Data - MSC2437

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#314]
In order to be able to restore the favourite messages in Tchap, we have to support the tagged events `m.tagged_events` in Room Account Data [MSC2437](https://github.com/matrix-org/matrix-doc/blob/giomfo/tagged_events/proposals/2437-tagged-events-account-data.md)

The support of these events has been added in the previous matrtix-android-sdk: https://github.com/matrix-org/matrix-android-sdk/pull/531
FYI this was done in matrix-ios-sdk too: https://github.com/matrix-org/matrix-ios-sdk/pull/959

We request here to add the support of the tagged events in the element-android-sdk

**Comment by Florian14** [comment]
https://github.com/vector-im/element-android/pull/4753
