### ISSUE TITLE
Translate the error observed when the user is not allowed to join a room 

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#336]
When the user clicks on a permalink related to a room where he's not invited, he got the following error:
![image](https://user-images.githubusercontent.com/8969772/147575950-f8986f4d-4e4c-4f46-b119-f00346c36000.png)

We have to translate this error in French

**Comment by ClaireGizard** [comment]
PR in Element: https://github.com/vector-im/element-android/pull/4848

**Comment by giomfo** [comment]
The translation of this error will be get from the Element-Android during one of the following rebases
