### ISSUE TITLE
[Settings] Add a link to a help page from Help&About screen

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#342]
Element-Android added recently a new section "Help" in the "Help & About " settings page in order to suggest a link to a specific web page dedicated to the user support: https://element.io/help

![help_and_about](https://user-images.githubusercontent.com/8969772/147824218-8cafc84c-908a-45fe-bd19-804b3862a9db.gif)

We currently hidden this section in Tchap v2.
@jdauphant do you want to set up this option for Tchap? I let you provide the url of this help page, if you want to turn on this option

**Comment by JDixmier** [comment]
URL to new FAQ : https://tchap.beta.gouv.fr/faq
