### ISSUE TITLE
Prompt the last admin before letting them leave a room

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#345]
Currently the last admin is prompted like any other members
![image](https://user-images.githubusercontent.com/8969772/148068777-bd5273db-2a21-45d6-b915-44b5be368905.png)

In Tchap, only the moderators and the admin are allowed to invite new members. And we want to prevent a room from being without admin. So in TchapV1, the following message was displayed when the end user was the last admin:
![image](https://user-images.githubusercontent.com/8969772/148069174-cc38e7bf-3373-4eb3-9b8d-2e37add5354f.png)

I request here to add the message: "Il ne sera plus administré..." as soon as the end user is the last admin even if the room join rule is public. We will keep the Element-Android message "Ce salon n'est pas public.... " in case of a private room, if the end user is not the last admin.
Note: We will keep the naming "salon" in the wording

I let you check in TchapV1 implementation how we detected the last admin

**Comment by ClaireGizard** [comment]
If last admin:
 -> Private room -> "Il ne sera plus administré....."
 -> Public room -> "Il ne sera plus administré....."
 If not the last admin: 
 -> Private room -> "Ce salon n'est pas public....."
 -> Public room -> ""

**Comment by giomfo** [comment]
> Note: We will keep the naming "salon" in the wording

@ClaireGizard this remark concerns the first paragraph of the message too. I prefer switch back the wording on the Element one:
"Quitter le salon
Voulez vous vraiment quitter le salon?"

**Comment by giomfo** [comment]
ok
