### ISSUE TITLE
[Dark mode] Improve the contrast in the incoming verification request

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#347]
In dark mode the contrast in the incoming verification request is too low for the buttons
![image](https://user-images.githubusercontent.com/8969772/148127679-1357d85e-97f5-49d3-99a5-f21e8cbe0045.png)

I suggest changing the banner background color which is arbitrary

**Comment by ClaireGizard** [comment]
Screen on Light:
![Screenshot_1642086306](https://user-images.githubusercontent.com/15031750/149357378-69ddb584-19e6-4191-b778-16d75a52ad16.png)

**Comment by areox-net** [comment]
For contrast, I suggest using simply white or a really light blue #D8EBFF;
