### ISSUE TITLE
Rename the unsigned APKs

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#360]
Currently the built unsigned apks have the prefix "vector-" ([see](https://github.com/tchapgouv/tchap-android-v2/actions/runs/1435565028)). They have to be renamed.

The expected packages are:
- TchapGplayWithoutvoipWithpinning-release-unsigned(instead of "vector-GplayAgentWithoutvoipWithpinning-release-unsigned")
- TchapFdroidWithoutvoipWithoutpinning-release-unsigned (instead of "vector-FdroidAgentWithoutvoipWithoutpinning-release-unsigned)
- BtchapGplayWithoutvoip**Withpinning**-release-unsigned (instead of "vector-GplayPreprodWithoutvoipWithoutpinning-release-unsigned" - CAUTION I changed here the dimension "pinning" for this package, I think more relevant to be aligned to the prod apk)
- BtchapFdroidWithoutvoipWithoutpinning-release-unsigned (instead of "vector-FdroidPreprodWithoutvoipWithoutpinning-release-unsigned)

The name of the apks expected in these packages are (in the same order):
- "gplay-tchap-withoutvoip-withpinning-_archi_-release-unsigned.apk" (instead of vector-gplay-agent-withoutvoip-withpinning-_archi_-release-unsigned.apk) 
- "fdroid-tchap-withoutvoip-withoutpinning-_archi_-release-unsigned.apk" (instead of vector-fdroid-agent-withoutvoip-withoutpinning-_archi_-release-unsigned.apk)
- "gplay-btchap-withoutvoip-withpinning-_archi_-release-unsigned.apk" (instead of vector-gplay-preprod-withoutvoip-withpinning-_archi_-release-unsigned.apk)  
- "fdroid-btchap-withoutvoip-withoutpinning-_archi_-release-unsigned.apk" (instead of vector-gplay-preprod-withoutvoip-withoutpinning-_archi_-release-unsigned.apk) 

I would have 2 additional requests
- can we stop building the "universal" apk by default, or at least stop adding it to the resulting package? I don't see the reason to  store it
- **can we replace in the apk name the pattern "release" with the actual tag (without "tchap_" prefix)? For example "v1.99.3" for the tag `tchap_v1.99.3`**

**Comment by yostyle** [comment]
> * can we stop building the "universal" apk by default, or at least stop adding it to the resulting package? I don't see the reason to  store it

Yes you can do it in `vector/build.gradle` by updating `universalApk true`

**Comment by yostyle** [comment]
> * can we replace in the apk name the pattern "release" with the actual tag (without "tchap_" prefix)? For example "v1.99.3" for the tag `tchap_v1.99.3`

By default Gradle uses APK filenames using the following scheme:
`modulename-screendensityABI-buildvariant.apk`

You can override the `outputFilename` value on each variant : https://stackoverflow.com/a/59583066
