### ISSUE TITLE
The apk generated on new tag have the unexpected prefix "-dev"

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#390]
for example: https://github.com/tchapgouv/tchap-android-v2/actions/runs/1752085797

I got from the generated package "gplay-tchap-withoutvoip-withpinning-x86_64-v1.99.4-dev-unsigned.apk"

**Comment by Florian14** [comment]
Currently, the `-dev` is added according to the absence of a tag in the current commit whereas Element checks if the current branch is not the `main`. There is no reason to have different behaviour in Tchap, I think that we can restore the Element's strategy.

**Comment by giomfo** [comment]
done
