### ISSUE TITLE
[Invitation by email] Handle correctly Id server consent

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android-v2#392]
Display error in the error popup (send invitation by email)
![Screenshot_1643378579](https://user-images.githubusercontent.com/15031750/151563827-1eb1c441-e94b-4308-8016-3011959b4cd1.png)

**Comment by giomfo** [comment]
This may be due to https://github.com/tchapgouv/tchap-android-v2/pull/293/files

We will patch it by forcing the consent on lookup error (see the code:  https://github.com/tchapgouv/tchap-android-v2/pull/293/files)

**Comment by giomfo** [comment]
fixed
