### ISSUE TITLE
Fix FCM token error in push notifications

### ISSUE THREAD

**Issue by Florian14** [tchapgouv/tchap-android-v2#402]
Push notifications are not working on my device with Tchap Tatin 1.99.4 in a Galaxy A10s, Android 11.

The notifications troubleshoot show an error with the Firebase Token mentioning a FIS_AUTH_ERROR.

![image](https://user-images.githubusercontent.com/11990514/152122977-2ab1ed67-7b4d-4171-b31a-51b80692a1f5.png)

**Comment by Florian14** [comment]
It seems that it is a regression after merging #375 , Token is retrieved successfully after reverting the commit. We should probably update the firebase settings considering the new Tchap packages.

**Comment by jdauphant** [comment]
Same error 
![image](https://user-images.githubusercontent.com/1238254/152208905-5f24356b-8ef4-416a-9fc8-96375816ce03.png)
Tchap Tatin 1.99.4 in a Galaxy A8 Android 9

**Comment by giomfo** [comment]
@Florian14 did you read https://github.com/vector-im/element-android/issues/5038#issuecomment-1024972133
they referred https://gitlab.com/quidsup/notrack-blocklists/-/issues/62

**Comment by Florian14** [comment]
> Same error ![image](https://user-images.githubusercontent.com/1238254/152208905-5f24356b-8ef4-416a-9fc8-96375816ce03.png) Tchap Tatin 1.99.4 in a Galaxy A8 Android 9

@jdauphant please can you try again with the previous release 1.99.3?

**Comment by jdauphant** [comment]
@Florian14 Same error in 1.99.3-dev
![image](https://user-images.githubusercontent.com/1238254/152395463-f4f2c1ea-78fe-45e5-971b-396f31ecb4e4.png)

**Comment by jdauphant** [comment]
(I have clean up and reinstalled the app)

**Comment by giomfo** [comment]
fixed
