### ISSUE TITLE
Change string "Tchap ne supporte pas encore les appels" to "Tchap ne supporte pas les appels"

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android-v2#410]
Change string "Tchap ne supporte pas encore les appels" to "Tchap ne supporte pas les appels".
![image](https://user-images.githubusercontent.com/1238254/152438345-2bbb159b-ccd0-4b8f-97d0-7b333b456a28.png)

#UnderPromiseOverDeliver

**Comment by giomfo** [comment]
done
