### ISSUE TITLE
[Room list] Update the font of the sender message

### ISSUE THREAD

**Issue by Florian14** [tchapgouv/tchap-android-v2#412]
Currently, the font and the text color of the sender in a message preview are too close to the room title.
We have to realign this to the Element design (ie. remove the `bold` from the sender style).

**Comment by areox-net** [comment]
For semplification, we can keep the same look as the Element base: the name of the author of the post is the same font-weight as the message, only in a darker color.

<img width="393" alt="1" src="https://user-images.githubusercontent.com/1255251/152564301-cc2f4fca-acfa-4427-b37b-5b117652a979.png">
