### ISSUE TITLE
1.99.4 does not request keys, for my account 

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-android-v2#415]
It looks like for my account, android 1.99.4 does not request keys automatically. The banner for starting the verification does not show.

I tried : 
 - android v1.2.3 : Banner shows, exchange happens with tchap-web. No problem.
 - android 1.99.4 : banner doesn't show. Other clients currently open : tchap-web and android 1.2.3 and another android 1.99.4 (I tried with one other client at a time, and with multiple)
 
Julien on the same phone does not have this problem.

A possible partial fix : add a link on encrypted messages, which triggers the exchange. This is what android 1.2.3 and tchap-web do.

**Comment by giomfo** [comment]
@Claire1817 can you please try to reproduce this issue with v2.0.0?

**Comment by Claire1817** [comment]
I reproduce the problem with v2.0.0
An application open on emulator and the other in real device.

**Comment by estellecomment** [comment]
In what case do I have no keys to share ? On first install ? When I have sent no messages yet ?

**Comment by giomfo** [comment]
> In what case do I have no keys to share ? On first install ? When I have sent no messages yet ?

when you didn't receive or send new messages since you logged in

**Comment by giomfo** [comment]
Cannot reproduce
We close this issue, @estellecomment don't hesitate to reopen it if you reproduce it
