### ISSUE TITLE
Simplify the main Conversations page

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-android-v2#417]
### Your use case

I propose to simplify the UI of the page by reducing the amount of displayed elements and information:

- Hiding the lock icon on avatars for private messages and salons
- Changing the icon for Forums, which is the only icon still displayed 
- Hiding the domain label for direct messages and private salons. The rule is "On Tchap everything is encrypted, private and restricted to public agents by default; we highlight only the exceptions"

A simpler, lighter UI will allow us to further mark the arrival of Tchap Tatin and improve perceived quality.

![1](https://user-images.githubusercontent.com/1255251/152844327-8deab099-7638-4e37-adb4-aedace970f0e.png)

**Comment by giomfo** [comment]
done
