### ISSUE TITLE
Error when click on "give consent" on add users in room screen

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android-v2#420]
I click on "inviter des utilisateurs" on a room that accept external user.
I search for an email "toto@element.io"
I click on "give consent".
I go a "HTTP 403" error.
![image](https://user-images.githubusercontent.com/1238254/153076951-a388a3d9-1947-4122-8f49-8b58227cd30e.png)

Device Android Xperia XZ1 compact
Tchap 1.99.4-dev
Android 9

**Comment by jdauphant** [comment]
By the way, I wanted to invite by email a new account by this way, apparently it's possible.

**Comment by Florian14** [comment]
This has been fixed in #392, this message should not be shown as the identity server terms are included in the global term and services of Tchap.
