### ISSUE TITLE
Wrong display of the forum icon in Dark theme

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android-v2#429]
In dark theme, the forum icon is not displayed correctly. There is a white block around the icon. 
This block is also visible in white theme when the background is not white.
Some screens:
![Screenshot_1644914471](https://user-images.githubusercontent.com/15031750/154026520-301ff74b-2100-48f9-b3f6-7faf84fab656.png)
![Screenshot_1644914840](https://user-images.githubusercontent.com/15031750/154026531-8685e5e7-e0ee-4375-88b0-8f1f33fa2bed.png)

**Comment by areox-net** [comment]
I created update the icon, which now has no background. Let's test how this works on avatars on both light and dark mode.
I took the opportunity to spec the dark mode of the "Create New Room" page. We could simply use the same dark grey of the image button on the top-left and the default light text for the 3 selection boxes. The other colors should work as they are.

<img width="393" alt="Salon-dark" src="https://user-images.githubusercontent.com/1255251/154035483-ca922e17-23b5-4112-82f6-f89d90228f9a.png">
