### ISSUE TITLE
Update Texts Color in a conversation

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android-v2#435]
Change the color of the message to grey (like Element)
Change the texte of the sender by the blue Tchap (#162D58)

**Comment by areox-net** [comment]
I confirm. It should look like this.
<img width="393" alt="1" src="https://user-images.githubusercontent.com/1255251/154732733-5e6f4ee2-f524-48f0-bcb1-5db1190ade75.png">

**Comment by jdauphant** [comment]
Nice. 
Can you put screenshots on your next visual PR ?
