### ISSUE TITLE
Text overlapping in the left panel

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#453]
When the text size is increased, the 2 options displayed at the bottom of the left panel overlap:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/8969772/155681799-c6ede873-e3fe-41b5-b401-07b578fe82cc.png">

This issue should be consider first in Element-Android

**Comment by Claire1817** [comment]
We had decided to hide the logout button in Tchap
