### ISSUE TITLE
Set up a new variant related to the new dev infra

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#459]
The existing variants will be renamed Tchap and Btchap

The new variant will be named: DevTchap

- URLs:
    - [matrix.agent1.tchap.incubateur.net](http://matrix.agent1.tchap.incubateur.net/)
    - [matrix.agent2.tchap.incubateur.net](http://matrix.agent2.tchap.incubateur.net/)
    - [matrix.externe.tchap.incubateur.net](http://matrix.externe.tchap.incubateur.net/)

**Comment by giomfo** [comment]
the logo will be 
![logo_tchap_color](https://user-images.githubusercontent.com/8969772/156588852-7b3a5363-0f80-4998-a8e0-ddcbdd445c59.png)

**Comment by areox-net** [comment]
Here is my proposition and the conresponding .svg file

![DEV-iOS-icon-squared](https://user-images.githubusercontent.com/1255251/156740607-7ac435bb-0d91-4cea-be2d-cf273731ecf2.png)

![DEV-iOS-icon-squared](https://user-images.githubusercontent.com/1255251/156740633-8e653713-ec8f-4a34-bc8b-7b4348f44892.svg)

@Claire1817 Could check if is working?
