### ISSUE TITLE
Il y a un problème d'ordre

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android-v2#485]
[tchap-android] [Element] Il y a un problème d'ordre

User message:

[Element] Il y a un problème d'ordre

User-Agent: "Tchap/2.0.3 (Linux; U; Android 9; G8441 Build/47.2.A.11.22; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "en_US"
device: "G8441"
device_id: "GIYFOYYTPJ"
locale: "en_US"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "9 (API 28) 3311891731-REL"
server_version: "undefined"
theme: "system"
user_id: "@julien.dauphant-beta.gouv.fr:agent.dinum.tchap.gouv.fr"
verbose_log: "OFF"

![image](https://user-images.githubusercontent.com/73166724/157857524-3cd42242-d834-4fc5-9f6d-b393a8b5d07c.png)

**Comment by giomfo** [comment]
dup of https://github.com/tchapgouv/tchap-android-v2/issues/484
