### ISSUE TITLE
Missing icon on the screen

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android-v2#486]
User-Agent: "Tchap/2.0.3 (Linux; U; Android 8.1.0; Moto G (5S) Plus Build/OPS28.65-36-1; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200031] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "false"
default_app_language: "fr_FR"
device: "Moto G (5S) Plus"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "8.1.0 (API 27) 63857-REL"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

![image](https://user-images.githubusercontent.com/1238254/158017205-f9dae44e-4350-40ef-ab42-6275d13a8ffa.png)

**Comment by giomfo** [comment]
@Jonathan2051 de quelle icone s'agit-il?

**Comment by jdauphant** [comment]
I have clean personnal data from the ticket : please don't do that anymore.
