### ISSUE TITLE
Absence de bouton ou flèche pour sortir d'une image

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android-v2#487]
Nouvelle version mobile : quand on clique sur une image reçue dans une discussion, il n'y a plus de bouton ou flèche pour quitter.

Dans la nouvelle appli mobile Tchap sur Samsung A40, Android 11, quand on clique sur une image (ex. ci-dessous), elle passe en plein écran et on ne peut pas quitter, il n’y a pas de bouton « retour » (sauf à connaitre les gestes système Android qui permettent de faire un retour arrière, mais tout le monde ne sait pas faire).

![image](https://user-images.githubusercontent.com/1238254/158017456-f590fdbc-8197-4a0b-b296-3aeca2d692ad.png)

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; SM-T725 Build/RP1A.200720.01; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "true"
default_app_language: "fr_FR"
device: "SM-T725"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) T725XXU2DUJ1-REL"
server_version: "undefined"
theme: "light"
verbose_log: "OFF"

**Comment by jdauphant** [comment]
I have clean personnal data from the ticket

**Comment by Claire1817** [comment]
This is the current behavior in Element.
If we want to improve this part, we should have a discussion with the design.
