### ISSUE TITLE
L'image des salons n'est plus hexagonale

### ISSUE THREAD

**Issue by Jonathan2051** [tchapgouv/tchap-android-v2#488]
L'image des salons n'est plus hexagonale et se confond avec les images rondes en principe réservées aussi personnes.

User-Agent: "Tchap/2.0.3 (Linux; U; Android 11; SM-T725 Build/RP1A.200720.01; Flavour GooglePlay; MatrixAndroidSdk2 1.3.12)"
Version: "2.0.3 [40200032] (G-836a1462-2022-03-07 12:38:20 +0100)"
app_language: "fr_FR"
branch_name: "main"
can_contact: "true"
default_app_language: "fr_FR"
device: "SM-T725"
device_id: "YEOSWECXRE"
locale: "fr_FR"
matrix_sdk_version: "1.3.12 (836a1462)"
multi_window: "OFF"
olm_version: "3.2.7 - olm version (3.2.7) - 2dbeea2-2021-12-06 11:01:21 -0500"
os: "11 (API 30) T725XXU2DUJ1-REL"
server_version: "undefined"
theme: "light"
user_id: "@david.tubert-dgccrf.finances.gouv.fr:agent.finances.tchap.gouv.fr"
verbose_log: "OFF"

**Comment by giomfo** [comment]
This will be considered internally as an design question (cross-platform)
