### ISSUE TITLE
Line break not taking properly

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android-v2#490]
For exemple : 
![image](https://user-images.githubusercontent.com/1238254/158019237-14cb7c8f-bcab-4b61-adb0-c14d8e2cf6ba.png)
But if I reply to the same message, line breaks are good :
![image](https://user-images.githubusercontent.com/1238254/158019260-3f1c9dd4-359d-46e3-96f9-9ea990d4ebc9.png)

On Tchap Web, it's good : 
![image](https://user-images.githubusercontent.com/1238254/158019297-0c9e294a-a0d2-4d99-aaa3-315e03d172c9.png)

**Comment by giomfo** [comment]
Selected to investigate and define a plan on this point

**Comment by giomfo** [comment]
@tchapgouv/bizdev FYI we stop investigation on this issue
Please ping the dev team here if you observed question/feedback on this point

**Comment by giomfo** [comment]
Please reopen it on new feedbacks
