### ISSUE TITLE
Design Tchap invite cells

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#79]
Currently the invites are displayed like this in tchap_v2:
![image](https://user-images.githubusercontent.com/8969772/118614069-a9c79d00-b7bf-11eb-80e4-f3edcef50e13.png)
and they were displayed like this in tchap_v1:
![image](https://user-images.githubusercontent.com/8969772/118614469-13e04200-b7c0-11eb-960c-8bf9c4eb4ce0.png)

We request here the following changes in tchap_v2 implementation:
- [x] reduce the avatar size to match with the size used in the room cells
- [x] apply a rounded avatar when the invite is related to a direct chat or a server notice. Use an hexagonal border in the other cases. No icon (padlock...) is expected on the avatar, because the information encrypted or not is not always available.
- [x] keep the 2 buttons order:  "Rejeter" and "Accepter", but change the policy of "Rejeter" to be uppercase (like "Accepter")
- [x] remove the chevron on the top right (Tchap doesn't propose the room preview for the moment), remove the code relative to the click handling
- [x] add a red badge in the section header with the number of invites (Note: I failed to see this badge in tchap_v2 whereas I see it in my element_android, something has been broken)
![image](https://user-images.githubusercontent.com/8969772/118672697-bb796680-b7f8-11eb-9b32-2a48ffe49e9f.png)

**Comment by Florian14** [comment]
@giomfo I didn't resize avatar as it was already matching the one used in the room cells.
Also, I didn't add the red badge as it should be fixed when tchap-v2 will be rebased on last release of element-android

**Comment by giomfo** [comment]
> I didn't resize avatar as it was already matching the one used in the room cells.

Ok, so I checked the point
