### ISSUE TITLE
[Home screen] cancel the search when the user selects an item from the search result

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-android-v2#97]
We added a search mode in the Home fragment during #61.
In case of search, the filtering is persistent when the user select an item and comes back.

We would like here to cancel/dismiss the search as soon as the user selects an item from the search result.
We may need to sync about this point with the platform team

**Comment by yostyle** [comment]
when we click on item (room or contact) it's possible to notify all fragments from the parent activity to cancel the search.

**Comment by yostyle** [comment]
another solution is to add an event observer in the parent fragment (homedetailfragment)

**Comment by Florian14** [comment]
In Tchap v2, the toolbar (which contains the search field) is hold by a parent fragment (the HomeFragment) which performs the search in sub fragments (Rooms and Users fragments). When an item is selected in those fragments, the event is not sent to the parent fragment, so we cannot close the search field.

A solution as mentioned by @yostyle would be to implement a Listener from the home fragment which will be triggered by children to close the search field

**Comment by giomfo** [comment]
linked to https://github.com/tchapgouv/tchap-android-v2/issues/52
